# Generated by Django 4.2.10 on 2025-02-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemtaskexecution',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemtaskexecution',
            name='task_args',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemtaskexecution',
            name='task_kwargs',
            field=models.JSONField(default=dict),
        ),
    ]
