services:
  webook:
    build:
      context: .
      dockerfile: Dockerfile
    image: "webook_app_staging:latest"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
  scheduler:
    build:
      context: .
      dockerfile: scheduler.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
  celery:
    image: "webook_app_staging:latest"
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "celery", "-A", "app.celery", "worker", "--loglevel=info" ]
  onlinebooking:
    build:
      context: onlinebooking_app/
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    restart: always
