services:
  webook:
    image: "ghcr.io/wemadefree/webook-nm:prod_stable"
    ports:
      - "8090:8080"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
  scheduler:
    build:
      context: .
      dockerfile: scheduler.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "celery", "-A", "app.celery", "worker", "--loglevel=info" ]
  onlinebooking:
    build:
      context: /onlinebooking_app/
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    restart: always
