services:
  elasticsearch:
    image: elasticsearch:7.17.25
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
    volumes:
      - ./data:/usr/share/elasticsearch/data
      # - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  elasticvue:
    image: cars10/elasticvue:latest
    ports:
      - "8080:8080"