# Generated by Django 3.2 on 2024-07-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0002_auto_20240715_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysegment',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citysegment_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='citysegment',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='citysegment',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='county',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='county_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='county',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='county',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='onlinebooking_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='school',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='school_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='school',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
