# Generated by Django 3.2 on 2024-07-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0003_auto_20240715_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='duration_amount',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='offset_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='minutes', max_length=10),
        ),
        migrations.AlterField(
            model_name='citysegment',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_segments', to='onlinebooking.county'),
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
