# Generated by Django 3.2 on 2024-07-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiendpoint_disabled'),
        ('onlinebooking', '0004_auto_20240716_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebooking',
            name='service_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.serviceaccount'),
        ),
    ]
