# Generated by Django 3.2 on 2024-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0005_alter_onlinebooking_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='title_format',
            field=models.CharField(default='%BookingNr% %Skolenavn% GUO', max_length=255),
            preserve_default=False,
        ),
    ]
