# Generated by Django 3.2 on 2024-07-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0006_onlinebookingsettings_title_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='visitors_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='onlinebooking.school'),
        ),
    ]
