# Generated by Django 3.2 on 2024-07-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0007_auto_20240718_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='segment_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
