# Generated by Django 3.2 on 2024-08-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0008_onlinebooking_segment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_number',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='County number'),
            preserve_default=False,
        ),
    ]
