# Generated by Django 3.2 on 2024-08-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0009_county_county_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='schools', to='arrangement.audience'),
        ),
    ]
