# Generated by Django 3.2 on 2024-08-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0010_school_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='arrangement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='onlinebooking', to='arrangement.arrangement'),
        ),
    ]
