# Generated by Django 3.2 on 2024-08-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0011_onlinebooking_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.location'),
        ),
        migrations.AlterField(
            model_name='onlinebookingsettings',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', max_length=10),
        ),
        migrations.AlterField(
            model_name='onlinebookingsettings',
            name='offset_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', max_length=10),
        ),
    ]
