# Generated by Django 3.2 on 2024-08-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0012_auto_20240814_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='arrangement_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangementtype'),
        ),
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='status_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.statustype'),
        ),
        migrations.AlterField(
            model_name='onlinebookingsettings',
            name='location',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.location'),
        ),
    ]
