# Generated by Django 3.2 on 2024-08-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20231023_1339'),
        ('onlinebooking', '0013_auto_20240814_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebookingsettings',
            name='main_planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='main_planner', to='arrangement.person'),
        ),
    ]
