# Generated by Django 3.2 on 2024-08-14 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinebooking', '0014_onlinebookingsettings_main_planner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebookingsettings',
            name='main_planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='main_planner', to=settings.AUTH_USER_MODEL),
        ),
    ]
