# Generated by Django 3.2 on 2024-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0016_remove_school_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='school_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
