# Generated by Django 3.2 on 2024-08-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0017_county_school_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebooking',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='onlinebooking',
            name='segment_text',
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='onlinebooking.county'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='onlinebooking.school'),
        ),
    ]
