# Generated by Django 3.2 on 2024-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0055_auto_20240820_1237'),
        ('onlinebooking', '0018_auto_20240816_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='audiences',
            field=models.ManyToManyField(to='arrangement.Audience'),
        ),
    ]
