# Generated by Django 3.2 on 2024-09-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arrangement", "0055_auto_20240820_1237"),
        ("onlinebooking", "0019_school_audiences"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinebookingsettings",
            name="audience_group",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="online_booking_settings",
                to="arrangement.audience",
            ),
            preserve_default=False,
        ),
    ]
