# Generated by Django 3.1.1 on 2021-10-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshour',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='confirmationreceipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={},
        ),
        migrations.AddField(
            model_name='eventservice',
            name='receipt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.confirmationreceipt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='businesshour',
            table='businesshours',
        ),
        migrations.AlterModelTable(
            name='calendar',
            table='calendars',
        ),
        migrations.AlterModelTable(
            name='confirmationreceipt',
            table='confirmationreceipts',
        ),
        migrations.AlterModelTable(
            name='eventservice',
            table='eventservices',
        ),
        migrations.AlterModelTable(
            name='note',
            table='Notes',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table='serviceproviders',
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table='servicetypes',
        ),
        migrations.AlterModelTable(
            name='timelineevent',
            table='timelineevents',
        ),
    ]
