# Generated by Django 3.1.1 on 2021-10-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0002_auto_20211015_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='owner', to='arrangement.person'),
            preserve_default=False,
        ),
    ]
