# Generated by Django 3.1.1 on 2022-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0003_auto_20220518_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name(English)'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name(English)'),
        ),
    ]
