# Generated by Django 3.1.1 on 2021-10-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0003_calendar_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='audience',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='businesshour',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='confirmationreceipt',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='eventservice',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owners', to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='confirmed_when',
            field=models.DateTimeField(null=True, verbose_name='ConfirmedWhen'),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='sent_when',
            field=models.DateTimeField(null=True, verbose_name='SentWhen'),
        ),
        migrations.AlterModelTable(
            name='arrangement',
            table=None,
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='audience',
            table=None,
        ),
        migrations.AlterModelTable(
            name='businesshour',
            table=None,
        ),
        migrations.AlterModelTable(
            name='calendar',
            table=None,
        ),
        migrations.AlterModelTable(
            name='confirmationreceipt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventservice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='note',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organizationtype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceprovider',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='timelineevent',
            table=None,
        ),
    ]
