# Generated by Django 3.1.1 on 2021-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0004_auto_20211018_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='organization_participants',
            field=models.ManyToManyField(related_name='participating_in', to='arrangement.Organization'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='people_participants',
            field=models.ManyToManyField(related_name='participating_in', to='arrangement.Person'),
        ),
    ]
