# Generated by Django 3.1.1 on 2022-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0004_auto_20220530_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='silo',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('arrangement_event', 'arrangement_event'), ('collision_event', 'collision_event'), ('holiday_event', 'holiday_event')], default='arrangement_event', max_length=255),
        ),
    ]
