# Generated by Django 3.1.1 on 2021-10-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0005_auto_20211018_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='icon_class',
            field=models.CharField(default=0, max_length=255, verbose_name='icon_class'),
            preserve_default=False,
        ),
    ]
