# Generated by Django 3.1.1 on 2022-06-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0005_auto_20220601_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='silo',
        ),
        migrations.AddField(
            model_name='event',
            name='associated_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='associated_events', to='arrangement.eventserie'),
        ),
        migrations.AddField(
            model_name='event',
            name='association_type',
            field=models.CharField(choices=[('no_association', 'no_association'), ('collision_resolved_originating_of_serie', 'collision_resolved_originating_of_serie')], default='no_association', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('arrangement_event', 'arrangement_event'), ('holiday_event', 'holiday_event')], default='arrangement_event', max_length=255),
        ),
    ]
