# Generated by Django 3.1.1 on 2021-10-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0006_audience_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, verbose_name='icon_class'),
        ),
    ]
