# Generated by Django 3.1.1 on 2022-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0006_auto_20220530_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='association_type',
            field=models.CharField(choices=[('no_association', 'no_association'), ('collision_resolved_originating_of_serie', 'collision_resolved_originating_of_serie')], default='no_association', max_length=255),
        ),
    ]
