# Generated by Django 3.1.1 on 2021-10-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0007_auto_20211018_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='all_day'),
            preserve_default=False,
        ),
    ]
