# Generated by Django 3.1.1 on 2022-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0007_auto_20220601_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('arrangement_event', 'arrangement_event'), ('holiday_event', 'holiday_event')], default='arrangement_event', max_length=255),
        ),
    ]
