# Generated by Django 3.1.1 on 2022-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0008_arrangement_meeting_place_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(related_name='my_events', to='arrangement.Person', verbose_name='People'),
        ),
    ]
