# Generated by Django 3.1.1 on 2021-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0008_event_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='ends',
            field=models.DateField(verbose_name='Ends'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='starts',
            field=models.DateField(verbose_name='Starts'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, verbose_name='IconClass'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_personal',
            field=models.BooleanField(default=True, verbose_name='IsPersonal'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='guid',
            field=models.CharField(db_index=True, max_length=68, unique=True, verbose_name='Guid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(verbose_name='AllDay'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sequence_guid',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='SequenceGuid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=1024, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='content',
            field=models.CharField(max_length=1024, verbose_name='Content'),
        ),
    ]
