# Generated by Django 3.1.1 on 2021-10-18 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0009_auto_20211018_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Stamp'),
            preserve_default=False,
        ),
    ]
