# Generated by Django 3.1.1 on 2022-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0009_auto_20220613_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='association_type',
            field=models.CharField(choices=[('no_association', 'no_association'), ('degraded_from_serie', 'degraded_from_serie'), ('collision_resolved_originating_of_serie', 'collision_resolved_originating_of_serie')], default='no_association', max_length=255),
        ),
    ]
