# Generated by Django 3.1.1 on 2022-06-27 06:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_auto_20220624_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='arrangementtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='full_name', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='roompreset',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True),
        ),
    ]
