# Generated by Django 3.1.1 on 2022-06-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0011_auto_20220624_1237'),
        ('arrangement', '0011_auto_20220622_1007'),
    ]

    operations = [
    ]
