# Generated by Django 3.1.1 on 2022-06-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0012_auto_20220627_0814'),
        ('arrangement', '0012_merge_20220627_0650'),
    ]

    operations = [
    ]
