# Generated by Django 3.1.1 on 2022-06-29 08:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0013_merge_20220627_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('file', models.FileField(upload_to='files_%(class)s/')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eventfile_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='arrangement.event')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_eventfile', to='arrangement.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
