# Generated by Django 3.1.1 on 2022-06-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0014_eventfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfile',
            old_name='event',
            new_name='associated_with',
        ),
    ]
