# Generated by Django 3.1.1 on 2022-06-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0016_auto_20220630_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangementfile',
            options={},
        ),
        migrations.RenameField(
            model_name='arrangementfile',
            old_name='arrangement',
            new_name='associated_with',
        ),
        migrations.AlterField(
            model_name='arrangementfile',
            name='file',
            field=models.FileField(upload_to='uploadedFiles/'),
        ),
        migrations.AlterField(
            model_name='arrangementfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_arrangementfile', to='arrangement.person'),
        ),
    ]
