# Generated by Django 3.1.1 on 2022-08-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0018_auto_20220803_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='after_buffer_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='after_buffer_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='before_buffer_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='before_buffer_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='buffer_after_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='after_buffer_for', to='arrangement.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='buffer_before_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='before_buffer_for', to='arrangement.event'),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='after_buffer_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='after_buffer_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='before_buffer_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='before_buffer_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='timezone',
            field=models.CharField(default='UTC', max_length=124),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='actual_visitors',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual visitors'),
        ),
        migrations.AlterField(
            model_name='event',
            name='actual_visitors',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual visitors'),
        ),
    ]
