# Generated by Django 3.1.1 on 2022-08-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0019_auto_20220810_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='associated_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='arrangement.event'),
        ),
    ]
