# Generated by Django 3.1.1 on 2022-09-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0020_auto_20220830_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementtype',
            name='self_nested_children',
            field=models.ManyToManyField(related_name='_arrangementtype_self_nested_children_+', to='arrangement.ArrangementType'),
        ),
    ]
