# Generated by Django 3.1.1 on 2022-09-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0022_auto_20220901_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangementtype',
            name='self_nested_children',
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_children', to='arrangement.arrangementtype'),
        ),
    ]
