# Generated by Django 3.1.1 on 2022-09-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0023_auto_20220901_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_children', to='arrangement.arrangementtype'),
        ),
    ]
