# Generated by Django 3.1.1 on 2022-09-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0024_auto_20220907_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangementtype',
            options={'verbose_name': 'Arrangement type', 'verbose_name_plural': 'Arrangement types'},
        ),
        migrations.AddField(
            model_name='audience',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_children', to='arrangement.audience'),
        ),
    ]
