# Generated by Django 3.1.1 on 2022-09-14 12:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import webook.utils.crudl_utils.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0025_auto_20220908_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, manager_name='all_objects', populate_from='name', unique=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statustype_archived_by', to='arrangement.person', verbose_name='Archived by')),
            ],
            options={
                'verbose_name': 'Status type',
                'verbose_name_plural': 'Status types',
            },
            bases=(models.Model, webook.utils.crudl_utils.model_mixins.ModelNamingMetaMixin),
        ),
    ]
