# Generated by Django 3.1.1 on 2022-09-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0027_statustype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='status_of_events', to='arrangement.statustype'),
        ),
    ]
