# Generated by Django 3.1.1 on 2022-09-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0028_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='status_of_arrangements', to='arrangement.statustype'),
        ),
    ]
