# Generated by Django 3.1.1 on 2022-09-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0030_planmanifest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrangement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangementtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.audience'),
        ),
    ]
