# Generated by Django 3.1.1 on 2022-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0033_auto_20220922_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='meeting_place',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='meeting_place_en',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
