# Generated by Django 3.1.1 on 2022-09-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0034_auto_20220922_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events_responsible_for', to='arrangement.person', verbose_name='Responsible'),
        ),
    ]
