# Generated by Django 3.1.1 on 2022-09-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0035_event_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='planmanifests_responsible_for', to='arrangement.person', verbose_name='Responsible'),
        ),
    ]
