# Generated by Django 3.1.1 on 2022-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0037_auto_20220927_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='display_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Display Text'),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='display_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Display Text(English)'),
        ),
    ]
