# Generated by Django 3.1.1 on 2022-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0039_auto_20221004_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='after_buffer_date_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='before_buffer_date_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='after_buffer_date_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='before_buffer_date_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
