# Generated by Django 3.1.1 on 2022-10-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0040_auto_20221004_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_provider_email',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Social Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='social_provider_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Social ID'),
        ),
    ]
