# Generated by Django 3.1.1 on 2022-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0041_auto_20221019_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
    ]
