# Generated by Django 3.1.1 on 2022-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0042_auto_20221109_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='internal_uuid',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
