# Generated by Django 3.1.1 on 2022-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0043_planmanifest_internal_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_before_collision_resolution',
            field=models.DateTimeField(default=None, null=True, verbose_name='End before collision resolution'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_before_collision_resolution',
            field=models.DateTimeField(default=None, null=True, verbose_name='Start before collision resolution'),
        ),
    ]
