# Generated by Django 3.1.1 on 2022-11-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0045_event_is_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_before_collision_resolution',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
