# Generated by Django 3.1.1 on 2022-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0046_event_title_before_collision_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='collision_resolution_behaviour',
            field=models.IntegerField(choices=[(0, 'Ignore colliding activities'), (1, 'Remove contested resources from activity on collisions')], default=0),
        ),
    ]
