# Generated by Django 3.1.1 on 2022-11-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0047_planmanifest_collision_resolution_behaviour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arrangements_responsible_for', to='arrangement.person', verbose_name='Responsible'),
        ),
    ]
