# Generated by Django 3.1.1 on 2023-01-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0048_auto_20221121_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='planners',
            field=models.ManyToManyField(null=True, to='arrangement.Person', verbose_name='Planners'),
        ),
    ]
