# Generated by Django 3.1.1 on 2022-04-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0001_initial'),
        ('arrangement', '0048_arrangement_show_on_multimedia_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='arrangement',
            name='display_layouts',
            field=models.ManyToManyField(related_name='arrangements', to='screenshow.DisplayLayout', verbose_name='Display Layout'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Screen Name English'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.note', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='event',
            name='display_layouts',
            field=models.ManyToManyField(related_name='events', to='screenshow.DisplayLayout', verbose_name='Display Layouts'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),
    ]
