# Generated by Django 3.1.1 on 2023-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0049_auto_20230116_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='planners',
            field=models.ManyToManyField(blank=True, null=True, to='arrangement.Person', verbose_name='Planners'),
        ),
    ]
