# Generated by Django 3.1.1 on 2022-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0049_auto_20220401_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Screen Name English'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name English'),
        ),

    ]
