# Generated by Django 3.1.1 on 2023-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0051_service_serviceemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='emails',
            field=models.ManyToManyField(related_name='services', to='arrangement.ServiceEmail'),
        ),
    ]
