# Generated by Django 3.1.1 on 2022-03-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0051_auto_20220329_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='ends',
            field=models.DateField(null=True, verbose_name='Ends'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='starts',
            field=models.DateField(null=True, verbose_name='Starts'),
        ),
    ]
