# Generated by Django 3.1.1 on 2022-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20220331_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (English)'),
        ),
    ]
