# Generated by Django 3.1.1 on 2022-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0052_auto_20220331_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='ticket_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Ticket Code'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Ticket Code'),
        ),
    ]
