# Generated by Django 3.1.1 on 2022-04-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0053_event_title_en'),
        ('arrangement', '0053_auto_20220413_0634'),
    ]

    operations = [
    ]
