# Generated by Django 3.1.1 on 2022-04-19 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0054_auto_20220419_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshour',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'Holiday')], default=0, verbose_name='Day Of Week'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.note', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Valid From'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='valid_through',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='Valid Through'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours',
            field=models.ManyToManyField(to='arrangement.BusinessHour', verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='room',
            name='business_hours',
            field=models.ManyToManyField(to='arrangement.BusinessHour', verbose_name='Business Hours'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='person',
            name='business_hours',
            field=models.ManyToManyField(to='arrangement.BusinessHour', verbose_name='Business Hours'),
        ),
        migrations.CreateModel(
            name='RoomPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('rooms', models.ManyToManyField(to='arrangement.Room')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
