# Generated by Django 3.1.1 on 2022-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0054_merge_20220413_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='meeting_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meeting Place'),
        ),
    ]
