# Generated by Django 4.2.10 on 2024-10-23 12:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooking', '0021_alter_onlinebookingsettings_audience_group'),
        ('arrangement', '0055_auto_20240820_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='booking_selected_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_booking_selected_audience', to='arrangement.audience', verbose_name='Selected Audience'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='city_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city_segment', to='onlinebooking.citysegment', verbose_name='City Segment'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_county', to='onlinebooking.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_school', to='onlinebooking.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='arrangementfile',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='arrangementfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_%(class)s', to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='arrangementtype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='article',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='confirmationreceipt',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='event',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_selected_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_booking_selected_audience', to='arrangement.audience', verbose_name='Selected Audience'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city_segment', to='onlinebooking.citysegment', verbose_name='City Segment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_county', to='onlinebooking.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to='arrangement.person', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='event',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_school', to='onlinebooking.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_updated_by', to='arrangement.person', verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_%(class)s', to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='eventserie',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='eventseriefile',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='eventseriefile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_%(class)s', to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='location',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='looseservicerequisition',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='note',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='person',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='booking_selected_audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_booking_selected_audience', to='arrangement.audience', verbose_name='Selected Audience'),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='city_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_city_segment', to='onlinebooking.citysegment', verbose_name='City Segment'),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_county', to='onlinebooking.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_school', to='onlinebooking.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='requisitionrecord',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='room',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='roompreset',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='serviceprovidable',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
    ]
