# Generated by Django 3.1.1 on 2022-04-20 12:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0055_auto_20220419_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompreset',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='25mill', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
