# Generated by Django 3.1.1 on 2022-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0055_arrangement_meeting_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='actual_visitors',
            field=models.IntegerField(default=0, verbose_name='Actual visitors'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='expected_visitors',
            field=models.IntegerField(default=0, verbose_name='Expected visitors'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_visitors',
            field=models.IntegerField(default=0, verbose_name='Actual visitors'),
        ),
        migrations.AddField(
            model_name='event',
            name='expected_visitors',
            field=models.IntegerField(default=0, verbose_name='Expected visitors'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket Code'),
        ),
    ]
