# Generated by Django 3.1.1 on 2023-01-27 13:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0055_serviceorder_ordered_for_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='freetext_comment',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='ordered_for_event',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='ordered_service',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='state',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='associated_manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arrangement.planmanifest'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='events',
            field=models.ManyToManyField(related_name='orders', to='arrangement.Event'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServiceOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('template', 'Template')], default='awaiting', max_length=10)),
                ('freetext_comment', models.TextField()),
                ('assigned_personell', models.ManyToManyField(related_name='services_assigned_to', to='arrangement.Person')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='arrangement.serviceorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='all_lines', to='arrangement.service')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
