# Generated by Django 3.1.1 on 2022-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0056_roompreset_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_screen',
            field=models.BooleanField(default=True, verbose_name='Has Screen'),
        ),
    ]
