# Generated by Django 4.2.10 on 2024-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0056_alter_arrangement_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
