# Generated by Django 3.1.1 on 2022-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0056_auto_20220413_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='Is Exclusive'),
        ),
    ]
