# Generated by Django 3.1.1 on 2023-01-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0056_auto_20230127_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderline',
            name='line_title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorderline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='associated_lines', to='arrangement.service'),
        ),
    ]
