# Generated by Django 3.1.1 on 2022-04-13 12:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0057_room_is_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangementFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='arrangementFiles/')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.arrangement')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
