# Generated by Django 3.1.1 on 2022-05-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0057_room_has_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arrangement_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='arrangementfile',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arrangementfile_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='arrangementfile',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='arrangementfile',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='arrangementtype_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='arrangementtype',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='article',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='article_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='article',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='audience',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audience_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='audience',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='audience',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='businesshour_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='businesshour',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='calendar_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='confirmationreceipt_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='confirmationreceipt',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='event',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='event_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='event',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eventservice_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='location',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='location_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='location',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='looseservicerequisition_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='looseservicerequisition',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='note',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='note_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='note',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organization_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='organization',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organizationtype_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='person',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='person_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='person',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='requisitionrecord',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requisitionrecord_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='requisitionrecord',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='requisitionrecord',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='room',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='room_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='room',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='roompreset',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='roompreset_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='roompreset',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='roompreset',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='serviceprovidable',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceprovidable_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='serviceprovidable',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='serviceprovidable',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servicetype_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='timelineevent_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
