# Generated by Django 4.2.10 on 2025-01-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0057_person_calendar_sync_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventserie',
            name='serie_plan_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_series', to='arrangement.planmanifest'),
        ),
    ]
