# Generated by Django 3.1.1 on 2022-04-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_arrangementfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementfiles',
            name='arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='arrangement.arrangement'),
        ),
        migrations.AlterField(
            model_name='arrangementfiles',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_arrangements', to='arrangement.person'),
        ),
    ]
