# Generated by Django 3.1.1 on 2022-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0003_auto_20220502_0805'),
        ('arrangement', '0058_auto_20220502_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='display_layouts',
            field=models.ManyToManyField(blank=True, related_name='arrangements', to='screenshow.DisplayLayout', verbose_name='Display Layout'),
        ),
        migrations.AlterField(
            model_name='eventserie',
            name='arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='series', to='arrangement.arrangement'),
        ),
        migrations.CreateModel(
            name='PlanManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('pattern', models.CharField(max_length=255)),
                ('pattern_strategy', models.CharField(max_length=255)),
                ('recurrence_strategy', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('stop_within', models.DateField(blank=True)),
                ('stop_after_x_occurences', models.IntegerField(blank=True)),
                ('project_x_months_into_future', models.IntegerField(blank=True)),
                ('display_layouts', models.ManyToManyField(to='screenshow.DisplayLayout')),
                ('people', models.ManyToManyField(to='arrangement.Person')),
                ('rooms', models.ManyToManyField(to='arrangement.Room')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSerieFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('file', models.FileField(upload_to='serieFiles/')),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='eventseriefile_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('event_serie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='arrangement.eventserie')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_uploaded_to_series', to='arrangement.person')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventserie',
            name='serie_plan_manifest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.planmanifest'),
            preserve_default=False,
        ),
    ]
