# Generated by Django 3.1.1 on 2023-01-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_auto_20230130_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='template_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.service'),
        ),
    ]
