# Generated by Django 3.1.1 on 2023-01-31 11:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0059_auto_20230130_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderProcessingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('recipient', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=512)),
                ('has_confirmed', models.BooleanField()),
                ('related_to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='arrangement.serviceorder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceOrderMailing',
        ),
    ]
