# Generated by Django 3.1.1 on 2022-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0059_auto_20220506_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='end_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='expected_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='start_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='title_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
