# Generated by Django 3.1.1 on 2022-04-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0059_auto_20220413_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArrangementFiles',
            new_name='ArrangementFile',
        ),
    ]
