# Generated by Django 3.1.1 on 2022-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0060_auto_20220506_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmanifest',
            name='project_x_months_into_future',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='stop_after_x_occurences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='stop_within',
            field=models.DateField(blank=True, null=True),
        ),
    ]
