# Generated by Django 3.1.1 on 2023-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0061_auto_20230131_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resources',
            field=models.ManyToManyField(to='arrangement.Person'),
        ),
    ]
