# Generated by Django 3.1.1 on 2022-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0062_auto_20220510_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='arbitrator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='day_of_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='interval',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
