# Generated by Django 3.1.1 on 2022-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0063_auto_20220510_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmanifest',
            name='arbitrator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='day_of_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='day_of_week',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='interval',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='month',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
