# Generated by Django 3.1.1 on 2023-02-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0063_serviceorderprovisionsininterim'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderprovisionsininterim',
            name='freetext_comment',
            field=models.TextField(blank=True),
        ),
    ]
