# Generated by Django 3.1.1 on 2022-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0064_auto_20220510_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmanifest',
            name='friday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='monday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='saturday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='sunday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='thursday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='tuesday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planmanifest',
            name='wednesday',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
