# Generated by Django 3.1.1 on 2023-02-08 10:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0064_serviceorderprovisionsininterim_freetext_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('freetext_comment', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.event')),
                ('related_to_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='arrangement.serviceorder')),
                ('selected_personell', models.ManyToManyField(related_name='interim_provisions_assigned_to', to='arrangement.Person')),
                ('sopr_resolving_this', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_resolved_provisions', to='arrangement.serviceorderprocessingrequest')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServiceOrderProvisionsInInterim',
        ),
    ]
