# Generated by Django 3.1.1 on 2022-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0003_auto_20220502_0805'),
        ('arrangement', '0065_auto_20220510_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display_layouts',
            field=models.ManyToManyField(blank=True, related_name='events', to='screenshow.DisplayLayout', verbose_name='Display Layouts'),
        ),
    ]
