# Generated by Django 3.1.1 on 2023-03-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0065_auto_20230208_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.person'),
        ),
        migrations.AlterField(
            model_name='serviceorderprovision',
            name='for_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisions', to='arrangement.event'),
        ),
    ]
