# Generated by Django 3.1.1 on 2022-05-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0066_auto_20220511_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name English'),
        ),
    ]
