# Generated by Django 3.1.1 on 2023-03-29 06:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0067_serviceorderprovision_comment_to_personell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderprovision',
            name='selected_personell',
            field=models.ManyToManyField(blank=True, null=True, related_name='interim_provisions_assigned_to', to='arrangement.Person'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('title', models.CharField(max_length=248)),
                ('source', models.CharField(max_length=512)),
                ('reference_to_url', models.URLField(null=True, verbose_name='Reference URL')),
                ('message', models.TextField(max_length=5012)),
                ('is_seen', models.BooleanField()),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notification_archived_by', to='arrangement.person', verbose_name='Archived by')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
