# Generated by Django 3.1.1 on 2022-05-18 05:11

from django.db import migrations, models
import webook.arrangement.models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0067_auto_20220516_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='has_personal_information',
            field=models.BooleanField(default=False, verbose_name='Has personal information'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='arrangementtype',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='full_name', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='roompreset',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='slug',
            field=webook.arrangement.models.ArchiveIrrespectiveAutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
