# Generated by Django 3.1.1 on 2023-03-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0068_auto_20230329_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arrangement.person'),
            preserve_default=False,
        ),
    ]
