# Generated by Django 3.1.1 on 2023-03-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0069_notification_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='arrangement.person'),
        ),
    ]
