# Generated by Django 3.1.1 on 2023-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0070_auto_20230329_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference_to_url',
            field=models.URLField(max_length=512, null=True, verbose_name='Reference URL'),
        ),
    ]
