# Generated by Django 3.1.1 on 2023-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0071_auto_20230329_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon_background_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
