# Generated by Django 3.1.1 on 2023-04-02 18:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0073_auto_20230401_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('changelog_message', models.TextField(max_length=5024)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.serviceorder')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
