# Generated by Django 3.1.1 on 2023-04-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0074_serviceorderchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderchangelog',
            name='source_sopr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='arrangement.serviceorderprocessingrequest'),
            preserve_default=False,
        ),
    ]
