# Generated by Django 3.1.1 on 2023-04-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0075_serviceorderchangelog_source_sopr'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceorder_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
        migrations.AlterField(
            model_name='serviceorderchangelog',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='arrangement.serviceorder'),
        ),
    ]
