# Generated by Django 3.1.1 on 2023-04-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0077_serviceorderpreconfiguration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrderChangelog',
            new_name='ServiceOrderInternalChangelog',
        ),
        migrations.AlterField(
            model_name='eventserie',
            name='serie_plan_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='series', to='arrangement.planmanifest'),
        ),
    ]
