# Generated by Django 3.1.1 on 2023-04-13 10:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0080_serviceorderchangesummary_service_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderchangesummary',
            name='has_been_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceorderchangeline',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initial_times', to='arrangement.serviceorderchangesummary'),
        ),
        migrations.CreateModel(
            name='ServiceOrderInitialTimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('date', models.DateField(verbose_name='Date')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceorderinitialtimerecord_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='arrangement.serviceorderchangesummary')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
