# Generated by Django 3.1.1 on 2023-04-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0081_auto_20230413_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderchangesummary',
            name='original_state_of_service_order',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('denied', 'Denied'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('changed', 'Changed'), ('template', 'Template'), ('in_revision', 'In Revision')], default='awaiting', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceorderchangeline',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='arrangement.serviceorderchangesummary'),
        ),
        migrations.AlterField(
            model_name='serviceorderinitialtimerecord',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='initial_times', to='arrangement.serviceorderchangesummary'),
        ),
    ]
