# Generated by Django 3.1.1 on 2023-04-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0083_auto_20230418_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderchangesummary',
            name='event',
        ),
        migrations.AddField(
            model_name='serviceorderchangesummary',
            name='event_provision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arrangement.serviceorderprovision'),
        ),
    ]
