# Generated by Django 3.1.1 on 2023-04-18 19:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0084_auto_20230418_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderChangeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived')),
                ('archived_when', models.DateTimeField(null=True, verbose_name='Archived when')),
                ('initial_start', models.DateTimeField()),
                ('initial_end', models.DateTimeField()),
                ('type_of_change', models.CharField(choices=[('new', 'New'), ('times_changed', 'Times Changed'), ('removed', 'Removed')], default='new', max_length=15)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceorderchangeline_archived_by', to='arrangement.person', verbose_name='Archived by')),
                ('provision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='arrangement.serviceorderprovision')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='serviceorderinitialtimerecord',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='serviceorderinitialtimerecord',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='serviceorderchangesummary',
            name='event_provision',
        ),
        migrations.RemoveField(
            model_name='serviceorderchangesummary',
            name='initial_event_end',
        ),
        migrations.RemoveField(
            model_name='serviceorderchangesummary',
            name='initial_event_start',
        ),
        migrations.RemoveField(
            model_name='serviceorderchangesummary',
            name='type',
        ),
        migrations.DeleteModel(
            name='ServiceOrderDateChangeLine',
        ),
        migrations.DeleteModel(
            name='ServiceOrderInitialTimeRecord',
        ),
        migrations.AddField(
            model_name='serviceorderchangeline',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='arrangement.serviceorderchangesummary'),
        ),
    ]
