# Generated by Django 3.1.1 on 2023-04-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0085_auto_20230418_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorderprovision',
            options={},
        ),
        migrations.AddField(
            model_name='serviceorderprovision',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceorderprovision_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='serviceorderprovision',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='serviceorderprovision',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
