# Generated by Django 3.1.1 on 2023-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0086_auto_20230418_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='people',
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='display_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Display Text (English)'),
        ),
    ]
