# Generated by Django 3.1.1 on 2023-06-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0088_auto_20230622_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderpreconfiguration',
            name='asssigned_personell',
            field=models.ManyToManyField(related_name='associated_with_preconfigurations', to='arrangement.Person'),
        ),
    ]
