# Generated by Django 3.1.1 on 2023-06-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0088_auto_20230622_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderprocessingrequest',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='serviceorderprocessingrequest_archived_by', to='arrangement.person', verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='serviceorderprocessingrequest',
            name='archived_when',
            field=models.DateTimeField(null=True, verbose_name='Archived when'),
        ),
        migrations.AddField(
            model_name='serviceorderprocessingrequest',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
