# Generated by Django 3.1.1 on 2023-06-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0089_auto_20230627_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderprocessingrequest',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='serviceorderprocessingrequest',
            name='archived_when',
        ),
        migrations.RemoveField(
            model_name='serviceorderprocessingrequest',
            name='is_archived',
        ),
    ]
