# Generated by Django 3.1.1 on 2023-06-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0089_serviceorderpreconfiguration_asssigned_personell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorderpreconfiguration',
            old_name='asssigned_personell',
            new_name='assigned_personell',
        ),
    ]
