# Generated by Django 3.1.1 on 2023-06-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0090_auto_20230627_1634'),
        ('arrangement', '0090_auto_20230623_1322'),
    ]

    operations = [
    ]
