# Generated by Django 3.1.1 on 2023-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0092_auto_20230630_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmanifest',
            name='vue_json',
            field=models.JSONField(default=dict),
        ),
    ]
