# Generated by Django 3.1.1 on 2023-07-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0093_planmanifest_vue_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmanifest',
            name='vue_json',
        ),
    ]
