# Generated by Django 3.1.1 on 2023-10-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0096_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_notes', to='arrangement.person'),
        ),
    ]
