# Generated by Django 3.1.1 on 2024-02-09 10:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0097_note_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanManifestDateExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField()),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planmanifest',
            name='exclusions',
            field=models.ManyToManyField(to='arrangement.PlanManifestDateExclusion'),
        ),
    ]
