# Generated by Django 3.1.1 on 2022-04-01 00:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayLayoutSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('html_template', models.TextField(verbose_name='HTML Template')),
                ('css_template', models.TextField(verbose_name='CSS Template')),
                ('file_output_path', models.TextField(blank=True, max_length=255, verbose_name='File Output Path')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('group_name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('group_name_en', models.CharField(max_length=255, null=True, verbose_name='Screen Group Name English')),
                ('quantity', models.IntegerField(default=10, verbose_name='Quantity')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='group_name', unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Screen Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Screen Name English')),
                ('quantity', models.IntegerField(default=10, verbose_name='Quantity')),
                ('is_room_screen', models.BooleanField(default=True, verbose_name='Is Screen in Room')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('screen_groups', models.ManyToManyField(to='screenshow.ScreenGroup', verbose_name='Screen Groups')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='screengroup',
            name='screens',
            field=models.ManyToManyField(to='screenshow.ScreenResource', verbose_name='Screen Resources'),
        ),
        migrations.CreateModel(
            name='DisplayLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('quantity', models.IntegerField(default=10, verbose_name='Quantity')),
                ('is_room_based', models.BooleanField(default=True, verbose_name='Is Room Based')),
                ('all_events', models.BooleanField(default=True, verbose_name='All Events')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Layout Active')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('groups', models.ManyToManyField(related_name='layouts', to='screenshow.ScreenGroup', verbose_name='Screen Groups')),
                ('screens', models.ManyToManyField(related_name='layouts', to='screenshow.ScreenResource', verbose_name='Screen Resources')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='screenshow.displaylayoutsetting', verbose_name='Display Layout Setting')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
