# Generated by Django 3.1.1 on 2022-04-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenresource',
            name='screen_groups',
            field=models.ManyToManyField(blank=True, to='screenshow.ScreenGroup', verbose_name='Screen Groups'),
        ),
    ]
