# Generated by Django 4.2.10 on 2024-11-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arrangement', '0057_person_calendar_sync_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arrangement.person')),
            ],
        ),
        migrations.CreateModel(
            name='SyncedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_event_id', models.CharField(max_length=100)),
                ('event_hash', models.CharField(max_length=100)),
                ('synced_counter', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('synced', 'Synced'), ('deleted', 'Deleted')], default='synced', max_length=10)),
                ('graph_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph_integration.graphcalendar')),
                ('webook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_events', to='arrangement.event')),
            ],
        ),
    ]
