# Generated by Django 4.2.10 on 2024-11-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0057_person_calendar_sync_enabled'),
        ('graph_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedevent',
            name='event_type',
            field=models.CharField(choices=[('repeating', 'repeating'), ('single', 'single')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='syncedevent',
            name='webook_serie_manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='synced_events', to='arrangement.planmanifest'),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='state',
            field=models.CharField(choices=[('pre_sync', 'pre_sync'), ('synced', 'synced'), ('deleted', 'deleted')], default='pre_sync', max_length=10),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='webook_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='synced_events', to='arrangement.event'),
        ),
    ]
