# Generated by Django 4.2.10 on 2024-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0003_graphcalendar_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphcalendar',
            name='calendar_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='graphcalendar',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='event_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='syncedevent',
            name='graph_event_id',
            field=models.CharField(max_length=255),
        ),
    ]
