# Generated by Django 4.2.10 on 2025-01-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0057_person_calendar_sync_enabled'),
        ('graph_integration', '0004_alter_graphcalendar_calendar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphcalendar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='arrangement.person'),
        ),
    ]
