# Generated by Django 4.2.10 on 2025-01-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_alter_eventserie_serie_plan_manifest'),
        ('graph_integration', '0005_alter_graphcalendar_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncedevent',
            name='webook_serie_manifest',
        ),
        migrations.AddField(
            model_name='syncedevent',
            name='webook_event_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='synced_events', to='arrangement.eventserie'),
        ),
    ]
