# Generated by Django 4.2.10 on 2025-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0006_remove_syncedevent_webook_serie_manifest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedevent',
            name='is_degraded_event',
            field=models.BooleanField(default=False),
        ),
    ]
