# Generated by Django 3.2 on 2024-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
