# Generated by Django 4.2.10 on 2024-10-24 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_apiendpoint_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='groups_allowed',
            field=models.ManyToManyField(related_name='endpoint_scopes', to='auth.group'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='users_directly_allowed',
            field=models.ManyToManyField(related_name='endpoint_scopes', to=settings.AUTH_USER_MODEL),
        ),
    ]
