# Generated by Django 4.2.10 on 2024-10-24 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_apiendpoint_groups_allowed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIEndpoint',
            new_name='APIScope',
        ),
    ]
