# Generated by Django 4.2.10 on 2024-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0004_rename_apiendpoint_apiscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this service account belongs to. A service account will get all API scopes granted to each of their groups.', related_name='service_accounts_set', related_query_name='service_account', to='auth.group', verbose_name='groups'),
        ),
    ]
