# Generated by Django 4.2.10 on 2025-01-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrangement', '0058_alter_eventserie_serie_plan_manifest'),
        ('api', '0005_serviceaccount_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_accounts', to='arrangement.person'),
        ),
    ]
