# Generated by Django 4.2.10 on 2025-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serviceaccount_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='service_account_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('google', 'Google')], default='normal', max_length=255),
        ),
    ]
