# Generated by Django 4.2.10 on 2025-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
