steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME
      - '--file'
      - Dockerfile.cloudrun
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME']
    id: Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - '-c'
      - >
        echo "FROM gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME
        
        COPY --from=gcr.io/cloudsql-docker/gce-proxy /cloud_sql_proxy 
        /cloudsql/cloud_sql_proxy" > Dockerfile-proxy;

        docker build -f Dockerfile-proxy -t gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy .
    id: Build proxy image
    entrypoint: /bin/bash
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy']
    id: Push proxy image
  - name: 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy'
    env:
      - DATABASE_HOST=127.0.0.1
    secretEnv: ['DATABASE_URL', 'DJANGO_SUPERUSER_PASSWORD', 'DJANGO_SECRET_KEY']
    args:
      - '-c'
      - >
        /cloudsql/cloud_sql_proxy
        -instances=${_INSTANCE_CONNECTION_NAME}=tcp:5432 & sleep 7;
        python manage.py migrate;
        ./initiasl_setup.sh
    id: Apply migrations
    entrypoint: /bin/bash
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', '$_CLOUDRUN_RESOURCE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
    id: Deploy
    entrypoint: gcloud
    #waitFor:
    #  - Push image
    #  - Apply migrations

images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _INSTANCE_CONNECTION_NAME: 'example:us-central1:myinstance'
  _REGION: 'europe-west1'
  _IMAGE_REPO: 'gcr.io'
  _IMAGE_BASENAME: 'webook'
  _CLOUDRUN_RESOURCE_NAME: 'webook-dev'


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/webook-django-dev-database-url/versions/latest
    env: 'DATABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/webook-django-dev-superuser-password/versions/latest
    env: 'DJANGO_SUPERUSER_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/webook-django-dev-secret-key/versions/latest
    env: 'DJANGO_SECRET_KEY'
