steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME:$COMMIT_SHA
      - '--file'
      - Dockerfile.cloudrun
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME:$COMMIT_SHA']
    id: Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - '-c'
      - >
        echo "FROM gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME:$COMMIT_SHA
        COPY --from=gcr.io/cloudsql-docker/gce_proxy /cloud_sql_proxy
        /cloudsql/cloud_sql_proxy" > Dockerfile-proxy;
        
        docker build -f Dockerfile-proxy -t gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy:$COMMIT_SHA .;
    id: Build proxy image
    entrypoint: bash
  - name: '$_IMAGE_BASENAME-cr-$BRANCH_NAME-proxy:$COMMIT_SHA'
    secretEnv: ['DATABASE_URL']
    args:
      - -instances=${_INSTANCE_CONNECTION_NAME}=tcp:5432
      - python manage.py migrate
    id: Apply migrations
    entrypoint: /cloudsql/cloud_sql_proxy
    waitFor:
      - Push image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', '$REPO_NAME', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
    id: Deploy
    entrypoint: gcloud
    waitFor:
      - Push image
      - Apply migrations
  
options:
  dynamicSubstitutions: true

substitutions:
  _INSTANCE_CONNECTION_NAME: 'example:us-central1:myinstance'
  _REGION: 'europe-west1'
  _IMAGE_REPO: 'gcr.io'
  _IMAGE_BASENAME: 'webook'


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WEBOOK_DJANGO_DEV_DATABASE_URL/versions/latest
    env: 'DATABASE_URL'
