# Generated by Django 3.1.1 on 2022-05-11 11:45

from django.db import migrations, models
import webook.users.media_pathing


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=webook.users.media_pathing.profile_picture_path, verbose_name='Profile Picture'),
        ),
    ]
