# Generated by Django 3.1.1 on 2022-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220907_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Oslo', max_length=255),
        ),
    ]
