# Generated by Django 3.1.1 on 2022-09-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220908_0632'),
        ('users', '0006_auto_20220824_0709'),
    ]

    operations = [
    ]
