# Generated by Django 3.1.1 on 2022-09-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220914_1438'),
        ('users', '0009_merge_20220914_0904'),
    ]

    operations = [
    ]