# Generated by Django 3.1.1 on 2022-10-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220927_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255),
        ),
    ]
