# Generated by Django 3.1.1 on 2023-01-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20221019_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_admin',
            field=models.BooleanField(default=False, verbose_name='User Administrator'),
        ),
    ]
