# Generated by Django 3.1.1 on 2024-06-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20231116_1356'),
        ('users', '0017_merge_20230113_1254'),
    ]

    operations = [
    ]
