# Generated by Django 3.2 on 2024-07-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_revokedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevokedToken',
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='allowed_endpoints',
        ),
        migrations.DeleteModel(
            name='APIEndpoint',
        ),
        migrations.DeleteModel(
            name='ServiceAccount',
        ),
    ]
