# Generated by Django 4.2.10 on 2024-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_loginaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginaudit',
            name='threshold_exceeded',
            field=models.BooleanField(default=False),
        ),
    ]
